#############################################################################
# Makefile for building: qde
# Generated by qmake (2.01a) (Qt 4.4.1) on: Wed Sep 3 15:30:07 2008
# Project:  qde.pro
# Template: subdirs
# Command: /opt/QTopia/bin/qmake -unix -o Makefile qde.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /opt/QTopia/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-qserver \
		sub-qdesktop \
		sub-qcopsender \
		sub-metadata

qserver/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qserver/ || $(MKDIR) qserver/ 
	cd qserver/ && $(QMAKE) qserver.pro -unix -o $(MAKEFILE)
sub-qserver-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qserver/ || $(MKDIR) qserver/ 
	cd qserver/ && $(QMAKE) qserver.pro -unix -o $(MAKEFILE)
sub-qserver: qserver/$(MAKEFILE) FORCE
	cd qserver/ && $(MAKE) -f $(MAKEFILE)
sub-qserver-make_default: qserver/$(MAKEFILE) FORCE
	cd qserver/ && $(MAKE) -f $(MAKEFILE) 
sub-qserver-make_first: qserver/$(MAKEFILE) FORCE
	cd qserver/ && $(MAKE) -f $(MAKEFILE) first
sub-qserver-all: qserver/$(MAKEFILE) FORCE
	cd qserver/ && $(MAKE) -f $(MAKEFILE) all
sub-qserver-clean: qserver/$(MAKEFILE) FORCE
	cd qserver/ && $(MAKE) -f $(MAKEFILE) clean
sub-qserver-distclean: qserver/$(MAKEFILE) FORCE
	cd qserver/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qserver-install_subtargets: qserver/$(MAKEFILE) FORCE
	cd qserver/ && $(MAKE) -f $(MAKEFILE) install
sub-qserver-uninstall_subtargets: qserver/$(MAKEFILE) FORCE
	cd qserver/ && $(MAKE) -f $(MAKEFILE) uninstall
qdesktop/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qdesktop/ || $(MKDIR) qdesktop/ 
	cd qdesktop/ && $(QMAKE) qdesktop.pro -unix -o $(MAKEFILE)
sub-qdesktop-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qdesktop/ || $(MKDIR) qdesktop/ 
	cd qdesktop/ && $(QMAKE) qdesktop.pro -unix -o $(MAKEFILE)
sub-qdesktop: qdesktop/$(MAKEFILE) FORCE
	cd qdesktop/ && $(MAKE) -f $(MAKEFILE)
sub-qdesktop-make_default: qdesktop/$(MAKEFILE) FORCE
	cd qdesktop/ && $(MAKE) -f $(MAKEFILE) 
sub-qdesktop-make_first: qdesktop/$(MAKEFILE) FORCE
	cd qdesktop/ && $(MAKE) -f $(MAKEFILE) first
sub-qdesktop-all: qdesktop/$(MAKEFILE) FORCE
	cd qdesktop/ && $(MAKE) -f $(MAKEFILE) all
sub-qdesktop-clean: qdesktop/$(MAKEFILE) FORCE
	cd qdesktop/ && $(MAKE) -f $(MAKEFILE) clean
sub-qdesktop-distclean: qdesktop/$(MAKEFILE) FORCE
	cd qdesktop/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qdesktop-install_subtargets: qdesktop/$(MAKEFILE) FORCE
	cd qdesktop/ && $(MAKE) -f $(MAKEFILE) install
sub-qdesktop-uninstall_subtargets: qdesktop/$(MAKEFILE) FORCE
	cd qdesktop/ && $(MAKE) -f $(MAKEFILE) uninstall
qcopsender/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qcopsender/ || $(MKDIR) qcopsender/ 
	cd qcopsender/ && $(QMAKE) qcopsender.pro -unix -o $(MAKEFILE)
sub-qcopsender-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qcopsender/ || $(MKDIR) qcopsender/ 
	cd qcopsender/ && $(QMAKE) qcopsender.pro -unix -o $(MAKEFILE)
sub-qcopsender: qcopsender/$(MAKEFILE) FORCE
	cd qcopsender/ && $(MAKE) -f $(MAKEFILE)
sub-qcopsender-make_default: qcopsender/$(MAKEFILE) FORCE
	cd qcopsender/ && $(MAKE) -f $(MAKEFILE) 
sub-qcopsender-make_first: qcopsender/$(MAKEFILE) FORCE
	cd qcopsender/ && $(MAKE) -f $(MAKEFILE) first
sub-qcopsender-all: qcopsender/$(MAKEFILE) FORCE
	cd qcopsender/ && $(MAKE) -f $(MAKEFILE) all
sub-qcopsender-clean: qcopsender/$(MAKEFILE) FORCE
	cd qcopsender/ && $(MAKE) -f $(MAKEFILE) clean
sub-qcopsender-distclean: qcopsender/$(MAKEFILE) FORCE
	cd qcopsender/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qcopsender-install_subtargets: qcopsender/$(MAKEFILE) FORCE
	cd qcopsender/ && $(MAKE) -f $(MAKEFILE) install
sub-qcopsender-uninstall_subtargets: qcopsender/$(MAKEFILE) FORCE
	cd qcopsender/ && $(MAKE) -f $(MAKEFILE) uninstall
metadata/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) metadata/ || $(MKDIR) metadata/ 
	cd metadata/ && $(QMAKE) metadata.pro -unix -o $(MAKEFILE)
sub-metadata-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) metadata/ || $(MKDIR) metadata/ 
	cd metadata/ && $(QMAKE) metadata.pro -unix -o $(MAKEFILE)
sub-metadata: metadata/$(MAKEFILE) FORCE
	cd metadata/ && $(MAKE) -f $(MAKEFILE)
sub-metadata-make_default: metadata/$(MAKEFILE) FORCE
	cd metadata/ && $(MAKE) -f $(MAKEFILE) 
sub-metadata-make_first: metadata/$(MAKEFILE) FORCE
	cd metadata/ && $(MAKE) -f $(MAKEFILE) first
sub-metadata-all: metadata/$(MAKEFILE) FORCE
	cd metadata/ && $(MAKE) -f $(MAKEFILE) all
sub-metadata-clean: metadata/$(MAKEFILE) FORCE
	cd metadata/ && $(MAKE) -f $(MAKEFILE) clean
sub-metadata-distclean: metadata/$(MAKEFILE) FORCE
	cd metadata/ && $(MAKE) -f $(MAKEFILE) distclean
sub-metadata-install_subtargets: metadata/$(MAKEFILE) FORCE
	cd metadata/ && $(MAKE) -f $(MAKEFILE) install
sub-metadata-uninstall_subtargets: metadata/$(MAKEFILE) FORCE
	cd metadata/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: qde.pro  /opt/QTopia/mkspecs/qws/linux-x86-g++/qmake.conf /opt/QTopia/mkspecs/common/unix.conf \
		/opt/QTopia/mkspecs/qconfig.pri \
		/opt/QTopia/mkspecs/features/qt_functions.prf \
		/opt/QTopia/mkspecs/features/qt_config.prf \
		/opt/QTopia/mkspecs/features/exclusive_builds.prf \
		/opt/QTopia/mkspecs/features/default_pre.prf \
		/opt/QTopia/mkspecs/features/release.prf \
		/opt/QTopia/mkspecs/features/default_post.prf \
		/opt/QTopia/mkspecs/features/warn_on.prf \
		/opt/QTopia/mkspecs/features/qt.prf \
		/opt/QTopia/mkspecs/features/unix/thread.prf \
		/opt/QTopia/mkspecs/features/moc.prf \
		/opt/QTopia/mkspecs/features/resources.prf \
		/opt/QTopia/mkspecs/features/uic.prf \
		/opt/QTopia/mkspecs/features/yacc.prf \
		/opt/QTopia/mkspecs/features/lex.prf
	$(QMAKE) -unix -o Makefile qde.pro
/opt/QTopia/mkspecs/common/unix.conf:
/opt/QTopia/mkspecs/qconfig.pri:
/opt/QTopia/mkspecs/features/qt_functions.prf:
/opt/QTopia/mkspecs/features/qt_config.prf:
/opt/QTopia/mkspecs/features/exclusive_builds.prf:
/opt/QTopia/mkspecs/features/default_pre.prf:
/opt/QTopia/mkspecs/features/release.prf:
/opt/QTopia/mkspecs/features/default_post.prf:
/opt/QTopia/mkspecs/features/warn_on.prf:
/opt/QTopia/mkspecs/features/qt.prf:
/opt/QTopia/mkspecs/features/unix/thread.prf:
/opt/QTopia/mkspecs/features/moc.prf:
/opt/QTopia/mkspecs/features/resources.prf:
/opt/QTopia/mkspecs/features/uic.prf:
/opt/QTopia/mkspecs/features/yacc.prf:
/opt/QTopia/mkspecs/features/lex.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -unix -o Makefile qde.pro

qmake_all: sub-qserver-qmake_all sub-qdesktop-qmake_all sub-qcopsender-qmake_all sub-metadata-qmake_all FORCE

make_default: sub-qserver-make_default sub-qdesktop-make_default sub-qcopsender-make_default sub-metadata-make_default FORCE
make_first: sub-qserver-make_first sub-qdesktop-make_first sub-qcopsender-make_first sub-metadata-make_first FORCE
all: sub-qserver-all sub-qdesktop-all sub-qcopsender-all sub-metadata-all FORCE
clean: sub-qserver-clean sub-qdesktop-clean sub-qcopsender-clean sub-metadata-clean FORCE
distclean: sub-qserver-distclean sub-qdesktop-distclean sub-qcopsender-distclean sub-metadata-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-qserver-install_subtargets sub-qdesktop-install_subtargets sub-qcopsender-install_subtargets sub-metadata-install_subtargets FORCE
uninstall_subtargets: sub-qserver-uninstall_subtargets sub-qdesktop-uninstall_subtargets sub-qcopsender-uninstall_subtargets sub-metadata-uninstall_subtargets FORCE

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

